name                     = "iai-web"
compatibility_date       = "2024-09-23"
compatibility_flags      = ["nodejs_compat"]
pages_build_output_dir   = ".next"

[[d1_databases]]
binding       = "DB"
database_name = "iai-db"
database_id   = "a806b0d9-027a-4887-ae7a-3abfbed04a2f"

[[kv_namespaces]]
binding    = "CACHE"
id         = "845da2404b6b44ac92d65b57966b221c"
preview_id = "599fb46d70e5434fba40f547e89d963d"

[env.production]
vars = {
  IAI_ENV  = "production",
  API_URL  = "https://api.iai.one",
  CDN_URL  = "https://cdn.iai.one"
}

[env.dev]
vars = {
  IAI_ENV  = "development",
  API_URL  = "http://localhost:8787",
  CDN_URL  = "http://localhost:8787"
}
