/* ═══════════════════════════════════════════════════════════════
   IAI Badge Definitions — The Full Ecosystem
   ═══════════════════════════════════════════════════════════════ */

import type { BadgeDefinition } from '@/types/badges'

export const BADGES: BadgeDefinition[] = [

  // ─────────────────────────────────────────────────────────────
  // PILLAR 1: TRUTH SHIELD  (cyan accent)
  // Recognizing those who protect the integrity of knowledge
  // ─────────────────────────────────────────────────────────────
  {
    id: 'TRUTH_SEEKER',
    name: 'Truth Seeker',
    lore: 'The first step toward wisdom is asking whether something is true.',
    description: 'Submit your first fact-check on any claim.',
    pillar: 'truth',
    tier: 'bronze',
    icon: '🔍',
    xp: 50,
    rarity: 60,
    phase: 1,
  },
  {
    id: 'MYTH_BUSTER',
    name: 'Myth Buster',
    lore: 'Misinformation thrives in silence. You chose to speak.',
    description: 'Successfully dispute 10 false claims with evidence.',
    pillar: 'truth',
    tier: 'silver',
    icon: '⚡',
    xp: 200,
    rarity: 25,
    phase: 1,
  },
  {
    id: 'ORACLE',
    name: 'Oracle',
    lore: 'You have seen through 100 illusions. The truth bends toward you.',
    description: 'Complete 100 fact-checks with ≥90% accuracy score.',
    pillar: 'truth',
    tier: 'gold',
    icon: '👁️',
    xp: 1000,
    rarity: 5,
    animated: true,
    phase: 1,
  },
  {
    id: 'SENTINEL',
    name: 'Sentinel',
    lore: 'Voted guardian of truth by the community itself.',
    description: 'Achieve Trusted Verifier status — 500+ community-approved fact-checks.',
    pillar: 'truth',
    tier: 'platinum',
    icon: '🛡️',
    xp: 5000,
    rarity: 1,
    animated: true,
    phase: 1,
  },
  {
    id: 'ETERNAL_LIGHT',
    name: 'Eternal Light',
    lore: 'In an age of noise, you became the signal. Rare as the stars that navigate.',
    description: 'Maintain 95%+ accuracy across 1,000 fact-checks. Top 0.1% of verifiers.',
    pillar: 'truth',
    tier: 'obsidian',
    icon: '✦',
    xp: 25000,
    rarity: 0.1,
    animated: true,
    phase: 1,
  },

  // ─────────────────────────────────────────────────────────────
  // PILLAR 2: KNOWLEDGE FORGE  (jade accent)
  // Honoring learners, educators, and knowledge builders
  // ─────────────────────────────────────────────────────────────
  {
    id: 'FIRST_LIGHT',
    name: 'First Light',
    lore: 'Every great mind begins with a single question answered.',
    description: 'Complete your first lesson on IAI.',
    pillar: 'knowledge',
    tier: 'bronze',
    icon: '🌱',
    xp: 30,
    rarity: 70,
    phase: 1,
  },
  {
    id: 'SCHOLAR',
    name: 'Scholar',
    lore: 'Ten lessons learned, ten paths opened.',
    description: 'Complete 10 lessons and pass their knowledge checks.',
    pillar: 'knowledge',
    tier: 'silver',
    icon: '📖',
    xp: 250,
    rarity: 30,
    phase: 1,
  },
  {
    id: 'SAGE',
    name: 'Sage',
    lore: 'You do not just learn. You understand. You transmit.',
    description: 'Complete 50 lessons and create at least 1 lesson of your own.',
    pillar: 'knowledge',
    tier: 'gold',
    icon: '🏮',
    xp: 1500,
    rarity: 8,
    animated: true,
    phase: 1,
  },
  {
    id: 'ARCHITECT_OF_MINDS',
    name: 'Architect of Minds',
    lore: 'Knowledge built a bridge. You built a cathedral.',
    description: 'Your 5+ lessons have been completed by 500+ learners.',
    pillar: 'knowledge',
    tier: 'platinum',
    icon: '🏛️',
    xp: 8000,
    rarity: 0.5,
    animated: true,
    phase: 1,
  },
  {
    id: 'FLAME_OF_AGES',
    name: 'Flame of Ages',
    lore: 'The torch you lit will outlive the century.',
    description: 'Create a lesson that is referenced by 10+ other creators and verified by IAI.',
    pillar: 'knowledge',
    tier: 'obsidian',
    icon: '🔥',
    xp: 50000,
    rarity: 0.05,
    animated: true,
    phase: 1,
  },

  // ─────────────────────────────────────────────────────────────
  // PILLAR 3: CREATOR GUILD  (gold accent)
  // Celebrating storytellers, artists, and original voices
  // ─────────────────────────────────────────────────────────────
  {
    id: 'INK_DROP',
    name: 'Ink Drop',
    lore: 'A single drop of ink can move a million minds.',
    description: 'Publish your first post on IAI.',
    pillar: 'creator',
    tier: 'bronze',
    icon: '✍️',
    xp: 40,
    rarity: 55,
    phase: 1,
  },
  {
    id: 'STORYTELLER',
    name: 'Storyteller',
    lore: 'You found your voice. Now others listen.',
    description: 'Publish 10 posts that earn 100+ total reactions.',
    pillar: 'creator',
    tier: 'silver',
    icon: '🪶',
    xp: 300,
    rarity: 20,
    phase: 1,
  },
  {
    id: 'RESONANCE',
    name: 'Resonance',
    lore: 'Your words rippled across the platform.',
    description: 'A single post reaches 1,000+ reactions.',
    pillar: 'creator',
    tier: 'gold',
    icon: '🌊',
    xp: 2000,
    rarity: 3,
    animated: true,
    phase: 1,
  },
  {
    id: 'VERIFIED_VOICE',
    name: 'Verified Voice',
    lore: 'Artistry and accuracy in equal measure — a rare gift.',
    description: '50+ posts published, all passing IAI fact-check.',
    pillar: 'creator',
    tier: 'platinum',
    icon: '💎',
    xp: 10000,
    rarity: 0.3,
    animated: true,
    phase: 1,
  },
  {
    id: 'LEGEND',
    name: 'Legend',
    lore: 'History will remember this name.',
    description: 'Your content has been cited, taught, and verified across 3+ categories with 10,000+ total reactions.',
    pillar: 'creator',
    tier: 'obsidian',
    icon: '⭐',
    xp: 100000,
    rarity: 0.01,
    animated: true,
    phase: 1,
  },

  // ─────────────────────────────────────────────────────────────
  // PILLAR 4: COMMUNITY HONORS  (amber/gold accent)
  // Honoring those who build the IAI ecosystem
  // ─────────────────────────────────────────────────────────────
  {
    id: 'PIONEER',
    name: 'Pioneer',
    lore: 'You came before the roads were built.',
    description: 'Join IAI as one of the first 1,000 users.',
    pillar: 'community',
    tier: 'gold',
    icon: '🧭',
    xp: 500,
    rarity: 2,
    phase: 1,
  },
  {
    id: 'CONNECTOR',
    name: 'Connector',
    lore: 'Ideas travel fastest between friends.',
    description: 'Build a network of 50 mutual connections.',
    pillar: 'community',
    tier: 'silver',
    icon: '🕸️',
    xp: 200,
    rarity: 18,
    phase: 2,
  },
  {
    id: 'CATALYST',
    name: 'Catalyst',
    lore: 'Your spark ignited a thousand conversations.',
    description: 'A post you wrote spawns 50+ reply discussions.',
    pillar: 'community',
    tier: 'gold',
    icon: '⚗️',
    xp: 1500,
    rarity: 4,
    phase: 1,
  },
  {
    id: 'PILLAR_OF_IAI',
    name: 'Pillar of IAI',
    lore: 'Without you, the house would be smaller.',
    description: 'Nominated by 100+ community members as a trusted contributor.',
    pillar: 'community',
    tier: 'platinum',
    icon: '🏺',
    xp: 7500,
    rarity: 0.2,
    animated: true,
    phase: 2,
  },

  // ─────────────────────────────────────────────────────────────
  // PILLAR 5: SPECIAL MARKS  (obsidian / multi-color)
  // Official, rare, and future-phase badges
  // ─────────────────────────────────────────────────────────────
  {
    id: 'IAI_VERIFIED',
    name: 'IAI Verified',
    lore: 'Confirmed authentic by the Intelligence · Artistry · International team.',
    description: 'Official verified account — given by IAI to notable creators, experts, and institutions.',
    pillar: 'special',
    tier: 'gold',
    icon: '✓',
    xp: 0,
    rarity: 0.5,
    phase: 1,
  },
  {
    id: 'TRUTH_ENGINE',
    name: 'Truth Engine',
    lore: 'You are no longer searching for truth. You have become its instrument.',
    description: 'AI-verified: 99%+ accuracy streak across 200 consecutive fact-checks.',
    pillar: 'special',
    tier: 'obsidian',
    icon: '⚙️',
    xp: 30000,
    rarity: 0.02,
    animated: true,
    phase: 1,
  },
  {
    id: 'IPFS_IMMORTAL',
    name: 'IPFS Immortal',
    lore: 'Your knowledge is now permanent. Censorship cannot reach you.',
    description: 'Your content has been pinned to IPFS — immortalized on the decentralized web.',
    pillar: 'special',
    tier: 'platinum',
    icon: '∞',
    xp: 5000,
    rarity: 1,
    animated: true,
    phase: 3,
  },
  {
    id: 'DAO_DELEGATE',
    name: 'DAO Delegate',
    lore: 'The future of IAI is shaped by voices like yours.',
    description: 'Elected governance delegate in the IAI DAO — Phase 3.',
    pillar: 'special',
    tier: 'platinum',
    icon: '🗳️',
    xp: 10000,
    rarity: 0.5,
    animated: true,
    phase: 3,
  },
  {
    id: 'GENESIS',
    name: 'Genesis',
    lore: 'You were here at the beginning of something that will outlast us all.',
    description: 'Awarded to the founding team and first 100 contributors of IAI.',
    pillar: 'special',
    tier: 'obsidian',
    icon: '🌌',
    xp: 99999,
    rarity: 0.001,
    animated: true,
    phase: 1,
  },
]

export const BADGE_MAP = Object.fromEntries(BADGES.map(b => [b.id, b]))

export const TIER_CONFIG = {
  bronze: {
    label: 'Bronze',
    color: '#CD7F32',
    glow: 'rgba(205,127,50,0.4)',
    border: 'rgba(205,127,50,0.6)',
    bg: 'rgba(205,127,50,0.08)',
  },
  silver: {
    label: 'Silver',
    color: '#C0C0C0',
    glow: 'rgba(192,192,192,0.4)',
    border: 'rgba(192,192,192,0.6)',
    bg: 'rgba(192,192,192,0.08)',
  },
  gold: {
    label: 'Gold',
    color: '#C9A84C',
    glow: 'rgba(201,168,76,0.5)',
    border: 'rgba(201,168,76,0.7)',
    bg: 'rgba(201,168,76,0.10)',
  },
  platinum: {
    label: 'Platinum',
    color: '#E5E4E2',
    glow: 'rgba(0,212,255,0.5)',
    border: 'rgba(229,228,226,0.8)',
    bg: 'rgba(0,212,255,0.08)',
  },
  obsidian: {
    label: 'Obsidian',
    color: '#9B59B6',
    glow: 'rgba(155,89,182,0.6)',
    border: 'rgba(155,89,182,0.8)',
    bg: 'rgba(155,89,182,0.12)',
  },
} as const

export const PILLAR_CONFIG = {
  truth: {
    label: 'Truth Shield',
    color: '#00D4FF',
    description: 'Recognizing those who protect the integrity of knowledge',
  },
  knowledge: {
    label: 'Knowledge Forge',
    color: '#00A878',
    description: 'Honoring learners, educators, and knowledge builders',
  },
  creator: {
    label: 'Creator Guild',
    color: '#C9A84C',
    description: 'Celebrating storytellers, artists, and original voices',
  },
  community: {
    label: 'Community Honors',
    color: '#F59E0B',
    description: 'Honoring those who build the IAI ecosystem',
  },
  special: {
    label: 'Special Marks',
    color: '#8B5CF6',
    description: 'Official, rare, and milestone badges',
  },
} as const
